export interface Airport {
  iata: string;
  city: string;
  country: string;
  name: string;
}

export const AIRPORTS: Airport[] = [
  { iata: "AAL", city: "Aalborg", country: "DK", name: "Aalborg Airport" },
  { iata: "ABJ", city: "Abidjan", country: "CI", name: "Felix-Houphouet-Boigny International Airport" },
  { iata: "ABQ", city: "Albuquerque", country: "US", name: "Albuquerque International Sunport" },
  { iata: "ABV", city: "Abuja", country: "NG", name: "Nnamdi Azikiwe International Airport" },
  { iata: "ACC", city: "Accra", country: "GH", name: "Kotoka International Airport" },
  { iata: "ADB", city: "Izmir", country: "TR", name: "Adnan Menderes Airport" },
  { iata: "ADL", city: "Adelaide", country: "AU", name: "Adelaide Airport" },
  { iata: "ADD", city: "Addis Ababa", country: "ET", name: "Bole International Airport" },
  { iata: "AEP", city: "Buenos Aires", country: "AR", name: "Aeroparque Jorge Newbery" },
  { iata: "AGP", city: "Malaga", country: "ES", name: "Malaga-Costa del Sol Airport" },
  { iata: "AKL", city: "Auckland", country: "NZ", name: "Auckland Airport" },
  { iata: "ALA", city: "Almaty", country: "KZ", name: "Almaty International Airport" },
  { iata: "ALC", city: "Alicante", country: "ES", name: "Alicante-Elche Airport" },
  { iata: "ALG", city: "Algiers", country: "DZ", name: "Houari Boumediene Airport" },
  { iata: "AMD", city: "Ahmedabad", country: "IN", name: "Sardar Vallabhbhai Patel International Airport" },
  { iata: "AMM", city: "Amman", country: "JO", name: "Queen Alia International Airport" },
  { iata: "AMS", city: "Amsterdam", country: "NL", name: "Amsterdam Airport Schiphol" },
  { iata: "ANC", city: "Anchorage", country: "US", name: "Ted Stevens Anchorage International Airport" },
  { iata: "ANU", city: "St. John's", country: "AG", name: "V.C. Bird International Airport" },
  { iata: "ARN", city: "Stockholm", country: "SE", name: "Stockholm Arlanda Airport" },
  { iata: "ASU", city: "Asuncion", country: "PY", name: "Silvio Pettirossi International Airport" },
  { iata: "ATH", city: "Athens", country: "GR", name: "Athens International Airport" },
  { iata: "ATL", city: "Atlanta", country: "US", name: "Hartsfield-Jackson Atlanta International Airport" },
  { iata: "AUH", city: "Abu Dhabi", country: "AE", name: "Abu Dhabi International Airport" },
  { iata: "AUS", city: "Austin", country: "US", name: "Austin-Bergstrom International Airport" },
  { iata: "AYT", city: "Antalya", country: "TR", name: "Antalya Airport" },
  { iata: "BAH", city: "Manama", country: "BH", name: "Bahrain International Airport" },
  { iata: "BCN", city: "Barcelona", country: "ES", name: "Josep Tarradellas Barcelona-El Prat Airport" },
  { iata: "BDL", city: "Hartford", country: "US", name: "Bradley International Airport" },
  { iata: "BEG", city: "Belgrade", country: "RS", name: "Belgrade Nikola Tesla Airport" },
  { iata: "BER", city: "Berlin", country: "DE", name: "Berlin Brandenburg Airport" },
  { iata: "BEY", city: "Beirut", country: "LB", name: "Rafic Hariri International Airport" },
  { iata: "BGO", city: "Bergen", country: "NO", name: "Bergen Airport Flesland" },
  { iata: "BGY", city: "Bergamo", country: "IT", name: "Milan Bergamo Airport" },
  { iata: "BHX", city: "Birmingham", country: "GB", name: "Birmingham Airport" },
  { iata: "BIO", city: "Bilbao", country: "ES", name: "Bilbao Airport" },
  { iata: "BJX", city: "Leon", country: "MX", name: "Del Bajio International Airport" },
  { iata: "BKK", city: "Bangkok", country: "TH", name: "Suvarnabhumi Airport" },
  { iata: "BLR", city: "Bangalore", country: "IN", name: "Kempegowda International Airport" },
  { iata: "BNA", city: "Nashville", country: "US", name: "Nashville International Airport" },
  { iata: "BNE", city: "Brisbane", country: "AU", name: "Brisbane Airport" },
  { iata: "BOD", city: "Bordeaux", country: "FR", name: "Bordeaux-Merignac Airport" },
  { iata: "BOG", city: "Bogota", country: "CO", name: "El Dorado International Airport" },
  { iata: "BOI", city: "Boise", country: "US", name: "Boise Airport" },
  { iata: "BOM", city: "Mumbai", country: "IN", name: "Chhatrapati Shivaji Maharaj International Airport" },
  { iata: "BOS", city: "Boston", country: "US", name: "Boston Logan International Airport" },
  { iata: "BRS", city: "Bristol", country: "GB", name: "Bristol Airport" },
  { iata: "BRU", city: "Brussels", country: "BE", name: "Brussels Airport" },
  { iata: "BSL", city: "Basel", country: "CH", name: "EuroAirport Basel-Mulhouse-Freiburg" },
  { iata: "BSB", city: "Brasilia", country: "BR", name: "Brasilia International Airport" },
  { iata: "BTS", city: "Bratislava", country: "SK", name: "Bratislava Airport" },
  { iata: "BUD", city: "Budapest", country: "HU", name: "Budapest Ferenc Liszt International Airport" },
  { iata: "BUF", city: "Buffalo", country: "US", name: "Buffalo Niagara International Airport" },
  { iata: "BWI", city: "Baltimore", country: "US", name: "Baltimore/Washington International Airport" },
  { iata: "CAI", city: "Cairo", country: "EG", name: "Cairo International Airport" },
  { iata: "CAN", city: "Guangzhou", country: "CN", name: "Guangzhou Baiyun International Airport" },
  { iata: "CCS", city: "Caracas", country: "VE", name: "Simon Bolivar International Airport" },
  { iata: "CCU", city: "Kolkata", country: "IN", name: "Netaji Subhas Chandra Bose International Airport" },
  { iata: "CDG", city: "Paris", country: "FR", name: "Charles de Gaulle Airport" },
  { iata: "CEB", city: "Cebu", country: "PH", name: "Mactan-Cebu International Airport" },
  { iata: "CFU", city: "Corfu", country: "GR", name: "Corfu International Airport" },
  { iata: "CGH", city: "Sao Paulo", country: "BR", name: "Congonhas Airport" },
  { iata: "CGO", city: "Zhengzhou", country: "CN", name: "Zhengzhou Xinzheng International Airport" },
  { iata: "CGK", city: "Jakarta", country: "ID", name: "Soekarno-Hatta International Airport" },
  { iata: "CGN", city: "Cologne", country: "DE", name: "Cologne Bonn Airport" },
  { iata: "CHC", city: "Christchurch", country: "NZ", name: "Christchurch Airport" },
  { iata: "CHS", city: "Charleston", country: "US", name: "Charleston International Airport" },
  { iata: "CKG", city: "Chongqing", country: "CN", name: "Chongqing Jiangbei International Airport" },
  { iata: "CLE", city: "Cleveland", country: "US", name: "Cleveland Hopkins International Airport" },
  { iata: "CLO", city: "Cali", country: "CO", name: "Alfonso Bonilla Aragon International Airport" },
  { iata: "CLT", city: "Charlotte", country: "US", name: "Charlotte Douglas International Airport" },
  { iata: "CMB", city: "Colombo", country: "LK", name: "Bandaranaike International Airport" },
  { iata: "CMH", city: "Columbus", country: "US", name: "John Glenn Columbus International Airport" },
  { iata: "CMN", city: "Casablanca", country: "MA", name: "Mohammed V International Airport" },
  { iata: "CNS", city: "Cairns", country: "AU", name: "Cairns Airport" },
  { iata: "CNX", city: "Chiang Mai", country: "TH", name: "Chiang Mai International Airport" },
  { iata: "COK", city: "Kochi", country: "IN", name: "Cochin International Airport" },
  { iata: "CPH", city: "Copenhagen", country: "DK", name: "Copenhagen Airport" },
  { iata: "CPT", city: "Cape Town", country: "ZA", name: "Cape Town International Airport" },
  { iata: "CRK", city: "Clark", country: "PH", name: "Clark International Airport" },
  { iata: "CTG", city: "Cartagena", country: "CO", name: "Rafael Nunez International Airport" },
  { iata: "CTS", city: "Sapporo", country: "JP", name: "New Chitose Airport" },
  { iata: "CTU", city: "Chengdu", country: "CN", name: "Chengdu Shuangliu International Airport" },
  { iata: "CUN", city: "Cancun", country: "MX", name: "Cancun International Airport" },
  { iata: "CUR", city: "Willemstad", country: "CW", name: "Curacao International Airport" },
  { iata: "CUZ", city: "Cusco", country: "PE", name: "Alejandro Velasco Astete International Airport" },
  { iata: "CWB", city: "Curitiba", country: "BR", name: "Afonso Pena International Airport" },
  { iata: "CVG", city: "Cincinnati", country: "US", name: "Cincinnati/Northern Kentucky International Airport" },
  { iata: "CWL", city: "Cardiff", country: "GB", name: "Cardiff Airport" },
  { iata: "DAC", city: "Dhaka", country: "BD", name: "Hazrat Shahjalal International Airport" },
  { iata: "DAD", city: "Da Nang", country: "VN", name: "Da Nang International Airport" },
  { iata: "DAR", city: "Dar es Salaam", country: "TZ", name: "Julius Nyerere International Airport" },
  { iata: "DCA", city: "Washington", country: "US", name: "Ronald Reagan Washington National Airport" },
  { iata: "DEL", city: "New Delhi", country: "IN", name: "Indira Gandhi International Airport" },
  { iata: "DEN", city: "Denver", country: "US", name: "Denver International Airport" },
  { iata: "DFW", city: "Dallas/Fort Worth", country: "US", name: "Dallas/Fort Worth International Airport" },
  { iata: "DKR", city: "Dakar", country: "SN", name: "Blaise Diagne International Airport" },
  { iata: "DLC", city: "Dalian", country: "CN", name: "Dalian Zhoushuizi International Airport" },
  { iata: "DME", city: "Moscow", country: "RU", name: "Moscow Domodedovo Airport" },
  { iata: "DMK", city: "Bangkok", country: "TH", name: "Don Mueang International Airport" },
  { iata: "DOH", city: "Doha", country: "QA", name: "Hamad International Airport" },
  { iata: "DPS", city: "Bali", country: "ID", name: "Ngurah Rai International Airport" },
  { iata: "DRS", city: "Dresden", country: "DE", name: "Dresden Airport" },
  { iata: "DSM", city: "Des Moines", country: "US", name: "Des Moines International Airport" },
  { iata: "DTW", city: "Detroit", country: "US", name: "Detroit Metropolitan Wayne County Airport" },
  { iata: "DUB", city: "Dublin", country: "IE", name: "Dublin Airport" },
  { iata: "DUR", city: "Durban", country: "ZA", name: "King Shaka International Airport" },
  { iata: "DUS", city: "Dusseldorf", country: "DE", name: "Dusseldorf Airport" },
  { iata: "DXB", city: "Dubai", country: "AE", name: "Dubai International Airport" },
  { iata: "EBB", city: "Entebbe", country: "UG", name: "Entebbe International Airport" },
  { iata: "EDI", city: "Edinburgh", country: "GB", name: "Edinburgh Airport" },
  { iata: "EIN", city: "Eindhoven", country: "NL", name: "Eindhoven Airport" },
  { iata: "ELP", city: "El Paso", country: "US", name: "El Paso International Airport" },
  { iata: "EMA", city: "East Midlands", country: "GB", name: "East Midlands Airport" },
  { iata: "ESB", city: "Ankara", country: "TR", name: "Esenboga International Airport" },
  { iata: "EVN", city: "Yerevan", country: "AM", name: "Zvartnots International Airport" },
  { iata: "EWR", city: "Newark", country: "US", name: "Newark Liberty International Airport" },
  { iata: "EZE", city: "Buenos Aires", country: "AR", name: "Ministro Pistarini International Airport" },
  { iata: "FAO", city: "Faro", country: "PT", name: "Faro Airport" },
  { iata: "FAT", city: "Fresno", country: "US", name: "Fresno Yosemite International Airport" },
  { iata: "FCO", city: "Rome", country: "IT", name: "Leonardo da Vinci-Fiumicino Airport" },
  { iata: "FLL", city: "Fort Lauderdale", country: "US", name: "Fort Lauderdale-Hollywood International Airport" },
  { iata: "FLR", city: "Florence", country: "IT", name: "Florence Airport" },
  { iata: "FNC", city: "Funchal", country: "PT", name: "Madeira Airport" },
  { iata: "FRA", city: "Frankfurt", country: "DE", name: "Frankfurt Airport" },
  { iata: "FUK", city: "Fukuoka", country: "JP", name: "Fukuoka Airport" },
  { iata: "GDL", city: "Guadalajara", country: "MX", name: "Miguel Hidalgo y Costilla Guadalajara International Airport" },
  { iata: "GDN", city: "Gdansk", country: "PL", name: "Gdansk Lech Walesa Airport" },
  { iata: "GIG", city: "Rio de Janeiro", country: "BR", name: "Rio de Janeiro-Galeao International Airport" },
  { iata: "GLA", city: "Glasgow", country: "GB", name: "Glasgow Airport" },
  { iata: "GMP", city: "Seoul", country: "KR", name: "Gimpo International Airport" },
  { iata: "GND", city: "St. George's", country: "GD", name: "Maurice Bishop International Airport" },
  { iata: "GOA", city: "Genoa", country: "IT", name: "Genoa Cristoforo Colombo Airport" },
  { iata: "GOI", city: "Goa", country: "IN", name: "Goa International Airport" },
  { iata: "GOT", city: "Gothenburg", country: "SE", name: "Gothenburg Landvetter Airport" },
  { iata: "GRR", city: "Grand Rapids", country: "US", name: "Gerald R. Ford International Airport" },
  { iata: "GUA", city: "Guatemala City", country: "GT", name: "La Aurora International Airport" },
  { iata: "GUM", city: "Hagatna", country: "GU", name: "Antonio B. Won Pat International Airport" },
  { iata: "GRU", city: "Sao Paulo", country: "BR", name: "Sao Paulo-Guarulhos International Airport" },
  { iata: "GVA", city: "Geneva", country: "CH", name: "Geneva Airport" },
  { iata: "GYE", city: "Guayaquil", country: "EC", name: "Jose Joaquin de Olmedo International Airport" },
  { iata: "HAK", city: "Haikou", country: "CN", name: "Haikou Meilan International Airport" },
  { iata: "HAJ", city: "Hanover", country: "DE", name: "Hanover Airport" },
  { iata: "HAM", city: "Hamburg", country: "DE", name: "Hamburg Airport" },
  { iata: "HAN", city: "Hanoi", country: "VN", name: "Noi Bai International Airport" },
  { iata: "HAV", city: "Havana", country: "CU", name: "Jose Marti International Airport" },
  { iata: "HEL", city: "Helsinki", country: "FI", name: "Helsinki-Vantaa Airport" },
  { iata: "HER", city: "Heraklion", country: "GR", name: "Heraklion International Airport" },
  { iata: "HGH", city: "Hangzhou", country: "CN", name: "Hangzhou Xiaoshan International Airport" },
  { iata: "HKG", city: "Hong Kong", country: "HK", name: "Hong Kong International Airport" },
  { iata: "HKT", city: "Phuket", country: "TH", name: "Phuket International Airport" },
  { iata: "HND", city: "Tokyo", country: "JP", name: "Tokyo Haneda Airport" },
  { iata: "HNL", city: "Honolulu", country: "US", name: "Daniel K. Inouye International Airport" },
  { iata: "HOU", city: "Houston", country: "US", name: "William P. Hobby Airport" },
  { iata: "HRG", city: "Hurghada", country: "EG", name: "Hurghada International Airport" },
  { iata: "HYD", city: "Hyderabad", country: "IN", name: "Rajiv Gandhi International Airport" },
  { iata: "IAD", city: "Washington", country: "US", name: "Washington Dulles International Airport" },
  { iata: "IAH", city: "Houston", country: "US", name: "George Bush Intercontinental Airport" },
  { iata: "IBZ", city: "Ibiza", country: "ES", name: "Ibiza Airport" },
  { iata: "ICN", city: "Seoul", country: "KR", name: "Incheon International Airport" },
  { iata: "IND", city: "Indianapolis", country: "US", name: "Indianapolis International Airport" },
  { iata: "INV", city: "Inverness", country: "GB", name: "Inverness Airport" },
  { iata: "ISB", city: "Islamabad", country: "PK", name: "Islamabad International Airport" },
  { iata: "IST", city: "Istanbul", country: "TR", name: "Istanbul Airport" },
  { iata: "JAI", city: "Jaipur", country: "IN", name: "Jaipur International Airport" },
  { iata: "JAX", city: "Jacksonville", country: "US", name: "Jacksonville International Airport" },
  { iata: "JED", city: "Jeddah", country: "SA", name: "King Abdulaziz International Airport" },
  { iata: "JER", city: "Jersey", country: "GB", name: "Jersey Airport" },
  { iata: "JFK", city: "New York", country: "US", name: "John F. Kennedy International Airport" },
  { iata: "JNB", city: "Johannesburg", country: "ZA", name: "O.R. Tambo International Airport" },
  { iata: "JTR", city: "Santorini", country: "GR", name: "Santorini Airport" },
  { iata: "KBP", city: "Kyiv", country: "UA", name: "Boryspil International Airport" },
  { iata: "KMG", city: "Kunming", country: "CN", name: "Kunming Changshui International Airport" },
  { iata: "KEF", city: "Reykjavik", country: "IS", name: "Keflavik International Airport" },
  { iata: "KHI", city: "Karachi", country: "PK", name: "Jinnah International Airport" },
  { iata: "KIN", city: "Kingston", country: "JM", name: "Norman Manley International Airport" },
  { iata: "KIX", city: "Osaka", country: "JP", name: "Kansai International Airport" },
  { iata: "KRK", city: "Krakow", country: "PL", name: "Krakow John Paul II International Airport" },
  { iata: "KTM", city: "Kathmandu", country: "NP", name: "Tribhuvan International Airport" },
  { iata: "KTW", city: "Katowice", country: "PL", name: "Katowice Airport" },
  { iata: "KUL", city: "Kuala Lumpur", country: "MY", name: "Kuala Lumpur International Airport" },
  { iata: "KWI", city: "Kuwait City", country: "KW", name: "Kuwait International Airport" },
  { iata: "LAS", city: "Las Vegas", country: "US", name: "Harry Reid International Airport" },
  { iata: "LAX", city: "Los Angeles", country: "US", name: "Los Angeles International Airport" },
  { iata: "LBA", city: "Leeds", country: "GB", name: "Leeds Bradford Airport" },
  { iata: "LCA", city: "Larnaca", country: "CY", name: "Larnaca International Airport" },
  { iata: "LED", city: "St. Petersburg", country: "RU", name: "Pulkovo Airport" },
  { iata: "LEJ", city: "Leipzig", country: "DE", name: "Leipzig/Halle Airport" },
  { iata: "LGA", city: "New York", country: "US", name: "LaGuardia Airport" },
  { iata: "LGW", city: "London", country: "GB", name: "London Gatwick Airport" },
  { iata: "LHE", city: "Lahore", country: "PK", name: "Allama Iqbal International Airport" },
  { iata: "LHR", city: "London", country: "GB", name: "London Heathrow Airport" },
  { iata: "LIM", city: "Lima", country: "PE", name: "Jorge Chavez International Airport" },
  { iata: "LIN", city: "Milan", country: "IT", name: "Milan Linate Airport" },
  { iata: "LIS", city: "Lisbon", country: "PT", name: "Humberto Delgado Airport" },
  { iata: "LJU", city: "Ljubljana", country: "SI", name: "Ljubljana Joze Pucnik Airport" },
  { iata: "LOS", city: "Lagos", country: "NG", name: "Murtala Muhammed International Airport" },
  { iata: "LPA", city: "Gran Canaria", country: "ES", name: "Gran Canaria Airport" },
  { iata: "LPB", city: "La Paz", country: "BO", name: "El Alto International Airport" },
  { iata: "LPL", city: "Liverpool", country: "GB", name: "Liverpool John Lennon Airport" },
  { iata: "LTN", city: "London", country: "GB", name: "London Luton Airport" },
  { iata: "LUN", city: "Lusaka", country: "ZM", name: "Kenneth Kaunda International Airport" },
  { iata: "LUX", city: "Luxembourg", country: "LU", name: "Luxembourg Airport" },
  { iata: "LYS", city: "Lyon", country: "FR", name: "Lyon-Saint Exupery Airport" },
  { iata: "MAA", city: "Chennai", country: "IN", name: "Chennai International Airport" },
  { iata: "MAD", city: "Madrid", country: "ES", name: "Adolfo Suarez Madrid-Barajas Airport" },
  { iata: "MAN", city: "Manchester", country: "GB", name: "Manchester Airport" },
  { iata: "MBJ", city: "Montego Bay", country: "JM", name: "Sangster International Airport" },
  { iata: "MCI", city: "Kansas City", country: "US", name: "Kansas City International Airport" },
  { iata: "MCO", city: "Orlando", country: "US", name: "Orlando International Airport" },
  { iata: "MCT", city: "Muscat", country: "OM", name: "Muscat International Airport" },
  { iata: "MDE", city: "Medellin", country: "CO", name: "Jose Maria Cordova International Airport" },
  { iata: "MDW", city: "Chicago", country: "US", name: "Chicago Midway International Airport" },
  { iata: "MED", city: "Medina", country: "SA", name: "Prince Mohammad bin Abdulaziz International Airport" },
  { iata: "MEL", city: "Melbourne", country: "AU", name: "Melbourne Airport" },
  { iata: "MEM", city: "Memphis", country: "US", name: "Memphis International Airport" },
  { iata: "MEX", city: "Mexico City", country: "MX", name: "Mexico City International Airport" },
  { iata: "MFM", city: "Macau", country: "MO", name: "Macau International Airport" },
  { iata: "MIA", city: "Miami", country: "US", name: "Miami International Airport" },
  { iata: "MKE", city: "Milwaukee", country: "US", name: "Milwaukee Mitchell International Airport" },
  { iata: "MLA", city: "Valletta", country: "MT", name: "Malta International Airport" },
  { iata: "MLE", city: "Male", country: "MV", name: "Velana International Airport" },
  { iata: "MNL", city: "Manila", country: "PH", name: "Ninoy Aquino International Airport" },
  { iata: "MPM", city: "Maputo", country: "MZ", name: "Maputo International Airport" },
  { iata: "MRS", city: "Marseille", country: "FR", name: "Marseille Provence Airport" },
  { iata: "MRU", city: "Mauritius", country: "MU", name: "Sir Seewoosagur Ramgoolam International Airport" },
  { iata: "MSP", city: "Minneapolis", country: "US", name: "Minneapolis-Saint Paul International Airport" },
  { iata: "MSY", city: "New Orleans", country: "US", name: "Louis Armstrong New Orleans International Airport" },
  { iata: "MTY", city: "Monterrey", country: "MX", name: "Monterrey International Airport" },
  { iata: "MUC", city: "Munich", country: "DE", name: "Munich Airport" },
  { iata: "MVD", city: "Montevideo", country: "UY", name: "Carrasco International Airport" },
  { iata: "MXP", city: "Milan", country: "IT", name: "Milan Malpensa Airport" },
  { iata: "NAN", city: "Nadi", country: "FJ", name: "Nadi International Airport" },
  { iata: "NAP", city: "Naples", country: "IT", name: "Naples International Airport" },
  { iata: "NAS", city: "Nassau", country: "BS", name: "Lynden Pindling International Airport" },
  { iata: "NBO", city: "Nairobi", country: "KE", name: "Jomo Kenyatta International Airport" },
  { iata: "NCE", city: "Nice", country: "FR", name: "Nice Cote d'Azur Airport" },
  { iata: "NCL", city: "Newcastle", country: "GB", name: "Newcastle Airport" },
  { iata: "NGO", city: "Nagoya", country: "JP", name: "Chubu Centrair International Airport" },
  { iata: "NKG", city: "Nanjing", country: "CN", name: "Nanjing Lukou International Airport" },
  { iata: "NRT", city: "Tokyo", country: "JP", name: "Narita International Airport" },
  { iata: "NNG", city: "Nanning", country: "CN", name: "Nanning Wuxu International Airport" },
  { iata: "NTE", city: "Nantes", country: "FR", name: "Nantes Atlantique Airport" },
  { iata: "NUE", city: "Nuremberg", country: "DE", name: "Nuremberg Airport" },
  { iata: "OAK", city: "Oakland", country: "US", name: "Oakland International Airport" },
  { iata: "OGG", city: "Maui", country: "US", name: "Kahului Airport" },
  { iata: "OKA", city: "Okinawa", country: "JP", name: "Naha Airport" },
  { iata: "OKC", city: "Oklahoma City", country: "US", name: "Will Rogers World Airport" },
  { iata: "OMA", city: "Omaha", country: "US", name: "Eppley Airfield" },
  { iata: "ONT", city: "Ontario", country: "US", name: "Ontario International Airport" },
  { iata: "OPO", city: "Porto", country: "PT", name: "Francisco Sa Carneiro Airport" },
  { iata: "ORD", city: "Chicago", country: "US", name: "O'Hare International Airport" },
  { iata: "ORK", city: "Cork", country: "IE", name: "Cork Airport" },
  { iata: "ORY", city: "Paris", country: "FR", name: "Paris Orly Airport" },
  { iata: "OSL", city: "Oslo", country: "NO", name: "Oslo Gardermoen Airport" },
  { iata: "OTP", city: "Bucharest", country: "RO", name: "Henri Coanda International Airport" },
  { iata: "OOL", city: "Gold Coast", country: "AU", name: "Gold Coast Airport" },
  { iata: "PAP", city: "Port-au-Prince", country: "HT", name: "Toussaint Louverture International Airport" },
  { iata: "PBI", city: "West Palm Beach", country: "US", name: "Palm Beach International Airport" },
  { iata: "PDL", city: "Ponta Delgada", country: "PT", name: "Joao Paulo II Airport" },
  { iata: "PDX", city: "Portland", country: "US", name: "Portland International Airport" },
  { iata: "PEK", city: "Beijing", country: "CN", name: "Beijing Capital International Airport" },
  { iata: "PEN", city: "Penang", country: "MY", name: "Penang International Airport" },
  { iata: "PER", city: "Perth", country: "AU", name: "Perth Airport" },
  { iata: "PHL", city: "Philadelphia", country: "US", name: "Philadelphia International Airport" },
  { iata: "PHX", city: "Phoenix", country: "US", name: "Phoenix Sky Harbor International Airport" },
  { iata: "PIT", city: "Pittsburgh", country: "US", name: "Pittsburgh International Airport" },
  { iata: "PKX", city: "Beijing", country: "CN", name: "Beijing Daxing International Airport" },
  { iata: "PMI", city: "Palma de Mallorca", country: "ES", name: "Palma de Mallorca Airport" },
  { iata: "PNH", city: "Phnom Penh", country: "KH", name: "Phnom Penh International Airport" },
  { iata: "POS", city: "Port of Spain", country: "TT", name: "Piarco International Airport" },
  { iata: "PPT", city: "Papeete", country: "PF", name: "Faaa International Airport" },
  { iata: "PRG", city: "Prague", country: "CZ", name: "Vaclav Havel Airport Prague" },
  { iata: "PSA", city: "Pisa", country: "IT", name: "Pisa International Airport" },
  { iata: "PTY", city: "Panama City", country: "PA", name: "Tocumen International Airport" },
  { iata: "PUJ", city: "Punta Cana", country: "DO", name: "Punta Cana International Airport" },
  { iata: "PUS", city: "Busan", country: "KR", name: "Gimhae International Airport" },
  { iata: "PVG", city: "Shanghai", country: "CN", name: "Shanghai Pudong International Airport" },
  { iata: "PVR", city: "Puerto Vallarta", country: "MX", name: "Licenciado Gustavo Diaz Ordaz International Airport" },
  { iata: "RAK", city: "Marrakech", country: "MA", name: "Marrakech Menara Airport" },
  { iata: "RDU", city: "Raleigh/Durham", country: "US", name: "Raleigh-Durham International Airport" },
  { iata: "REC", city: "Recife", country: "BR", name: "Recife/Guararapes International Airport" },
  { iata: "REP", city: "Siem Reap", country: "KH", name: "Siem Reap International Airport" },
  { iata: "RGN", city: "Yangon", country: "MM", name: "Yangon International Airport" },
  { iata: "RHO", city: "Rhodes", country: "GR", name: "Rhodes International Airport" },
  { iata: "RIC", city: "Richmond", country: "US", name: "Richmond International Airport" },
  { iata: "RIX", city: "Riga", country: "LV", name: "Riga International Airport" },
  { iata: "RNO", city: "Reno", country: "US", name: "Reno-Tahoe International Airport" },
  { iata: "RSW", city: "Fort Myers", country: "US", name: "Southwest Florida International Airport" },
  { iata: "RUH", city: "Riyadh", country: "SA", name: "King Khalid International Airport" },
  { iata: "SAN", city: "San Diego", country: "US", name: "San Diego International Airport" },
  { iata: "SAT", city: "San Antonio", country: "US", name: "San Antonio International Airport" },
  { iata: "SAV", city: "Savannah", country: "US", name: "Savannah/Hilton Head International Airport" },
  { iata: "SAW", city: "Istanbul", country: "TR", name: "Istanbul Sabiha Gokcen International Airport" },
  { iata: "SCL", city: "Santiago", country: "CL", name: "Arturo Merino Benitez International Airport" },
  { iata: "SDF", city: "Louisville", country: "US", name: "Louisville International Airport" },
  { iata: "SEA", city: "Seattle", country: "US", name: "Seattle-Tacoma International Airport" },
  { iata: "SEZ", city: "Mahe", country: "SC", name: "Seychelles International Airport" },
  { iata: "SFO", city: "San Francisco", country: "US", name: "San Francisco International Airport" },
  { iata: "SGN", city: "Ho Chi Minh City", country: "VN", name: "Tan Son Nhat International Airport" },
  { iata: "SHA", city: "Shanghai", country: "CN", name: "Shanghai Hongqiao International Airport" },
  { iata: "SHJ", city: "Sharjah", country: "AE", name: "Sharjah International Airport" },
  { iata: "SIN", city: "Singapore", country: "SG", name: "Singapore Changi Airport" },
  { iata: "SJC", city: "San Jose", country: "US", name: "San Jose International Airport" },
  { iata: "SJD", city: "San Jose del Cabo", country: "MX", name: "Los Cabos International Airport" },
  { iata: "SJO", city: "San Jose", country: "CR", name: "Juan Santamaria International Airport" },
  { iata: "SJU", city: "San Juan", country: "PR", name: "Luis Munoz Marin International Airport" },
  { iata: "SKG", city: "Thessaloniki", country: "GR", name: "Thessaloniki Airport Makedonia" },
  { iata: "SLC", city: "Salt Lake City", country: "US", name: "Salt Lake City International Airport" },
  { iata: "SMF", city: "Sacramento", country: "US", name: "Sacramento International Airport" },
  { iata: "SNA", city: "Santa Ana", country: "US", name: "John Wayne Airport" },
  { iata: "SNN", city: "Shannon", country: "IE", name: "Shannon Airport" },
  { iata: "SOF", city: "Sofia", country: "BG", name: "Sofia Airport" },
  { iata: "SRQ", city: "Sarasota", country: "US", name: "Sarasota-Bradenton International Airport" },
  { iata: "SSA", city: "Salvador", country: "BR", name: "Deputado Luis Eduardo Magalhaes International Airport" },
  { iata: "SSH", city: "Sharm el-Sheikh", country: "EG", name: "Sharm el-Sheikh International Airport" },
  { iata: "STI", city: "Santiago", country: "DO", name: "Cibao International Airport" },
  { iata: "STL", city: "St. Louis", country: "US", name: "St. Louis Lambert International Airport" },
  { iata: "STN", city: "London", country: "GB", name: "London Stansted Airport" },
  { iata: "STR", city: "Stuttgart", country: "DE", name: "Stuttgart Airport" },
  { iata: "SUB", city: "Surabaya", country: "ID", name: "Juanda International Airport" },
  { iata: "SVG", city: "Stavanger", country: "NO", name: "Stavanger Airport Sola" },
  { iata: "SVO", city: "Moscow", country: "RU", name: "Sheremetyevo International Airport" },
  { iata: "SVQ", city: "Seville", country: "ES", name: "Seville Airport" },
  { iata: "SXM", city: "St. Maarten", country: "SX", name: "Princess Juliana International Airport" },
  { iata: "SYD", city: "Sydney", country: "AU", name: "Sydney Kingsford Smith Airport" },
  { iata: "SZX", city: "Shenzhen", country: "CN", name: "Shenzhen Bao'an International Airport" },
  { iata: "TAS", city: "Tashkent", country: "UZ", name: "Islam Karimov Tashkent International Airport" },
  { iata: "TBS", city: "Tbilisi", country: "GE", name: "Tbilisi International Airport" },
  { iata: "TFN", city: "Tenerife", country: "ES", name: "Tenerife North Airport" },
  { iata: "TFS", city: "Tenerife", country: "ES", name: "Tenerife South Airport" },
  { iata: "TIA", city: "Tirana", country: "AL", name: "Tirana International Airport" },
  { iata: "TIJ", city: "Tijuana", country: "MX", name: "Tijuana International Airport" },
  { iata: "TLL", city: "Tallinn", country: "EE", name: "Lennart Meri Tallinn Airport" },
  { iata: "TLV", city: "Tel Aviv", country: "IL", name: "Ben Gurion Airport" },
  { iata: "TLS", city: "Toulouse", country: "FR", name: "Toulouse-Blagnac Airport" },
  { iata: "TPA", city: "Tampa", country: "US", name: "Tampa International Airport" },
  { iata: "TPE", city: "Taipei", country: "TW", name: "Taiwan Taoyuan International Airport" },
  { iata: "TRD", city: "Trondheim", country: "NO", name: "Trondheim Airport Vaernes" },
  { iata: "TRN", city: "Turin", country: "IT", name: "Turin Airport" },
  { iata: "TRV", city: "Thiruvananthapuram", country: "IN", name: "Trivandrum International Airport" },
  { iata: "TSA", city: "Taipei", country: "TW", name: "Taipei Songshan Airport" },
  { iata: "TSN", city: "Tianjin", country: "CN", name: "Tianjin Binhai International Airport" },
  { iata: "TUL", city: "Tulsa", country: "US", name: "Tulsa International Airport" },
  { iata: "TUN", city: "Tunis", country: "TN", name: "Tunis-Carthage International Airport" },
  { iata: "TUS", city: "Tucson", country: "US", name: "Tucson International Airport" },
  { iata: "UIO", city: "Quito", country: "EC", name: "Mariscal Sucre International Airport" },
  { iata: "ULN", city: "Ulaanbaatar", country: "MN", name: "Chinggis Khaan International Airport" },
  { iata: "VCE", city: "Venice", country: "IT", name: "Venice Marco Polo Airport" },
  { iata: "VIE", city: "Vienna", country: "AT", name: "Vienna International Airport" },
  { iata: "VLC", city: "Valencia", country: "ES", name: "Valencia Airport" },
  { iata: "VNO", city: "Vilnius", country: "LT", name: "Vilnius Airport" },
  { iata: "VRN", city: "Verona", country: "IT", name: "Verona Villafranca Airport" },
  { iata: "VTE", city: "Vientiane", country: "LA", name: "Wattay International Airport" },
  { iata: "WAW", city: "Warsaw", country: "PL", name: "Warsaw Chopin Airport" },
  { iata: "WLG", city: "Wellington", country: "NZ", name: "Wellington International Airport" },
  { iata: "WRO", city: "Wroclaw", country: "PL", name: "Wroclaw Nicolaus Copernicus Airport" },
  { iata: "WUH", city: "Wuhan", country: "CN", name: "Wuhan Tianhe International Airport" },
  { iata: "XIY", city: "Xi'an", country: "CN", name: "Xi'an Xianyang International Airport" },
  { iata: "YEG", city: "Edmonton", country: "CA", name: "Edmonton International Airport" },
  { iata: "YHZ", city: "Halifax", country: "CA", name: "Halifax Stanfield International Airport" },
  { iata: "YOW", city: "Ottawa", country: "CA", name: "Ottawa Macdonald-Cartier International Airport" },
  { iata: "YQB", city: "Quebec City", country: "CA", name: "Quebec City Jean Lesage International Airport" },
  { iata: "YUL", city: "Montreal", country: "CA", name: "Montreal-Trudeau International Airport" },
  { iata: "YVR", city: "Vancouver", country: "CA", name: "Vancouver International Airport" },
  { iata: "YWG", city: "Winnipeg", country: "CA", name: "Winnipeg James Armstrong Richardson International Airport" },
  { iata: "YYC", city: "Calgary", country: "CA", name: "Calgary International Airport" },
  { iata: "YYZ", city: "Toronto", country: "CA", name: "Toronto Pearson International Airport" },
  { iata: "ZAG", city: "Zagreb", country: "HR", name: "Franjo Tudman Airport" },
  { iata: "ZNZ", city: "Zanzibar", country: "TZ", name: "Abeid Amani Karume International Airport" },
  { iata: "ZRH", city: "Zurich", country: "CH", name: "Zurich Airport" },
];
